name: ⚠️ Security Report
description: File a security report
title: "[Security]: "
labels: ["type: security"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this security report!
              Before you create the issue:
              * Search the existing issues first, as yours may be a duplicate.
    - type: textarea
      id: security-issue
      attributes:
          label: Describe the security issue
          description: A clear and concise description of what the security issue is.
      validations:
          required: true
    - type: input
      id: cve
      attributes:
          label: CVE
          description: If applicable, add the CVE number here.
          placeholder: CVE-YYYY-XXXX
    - type: textarea
      id: additional-context
      attributes:
          label: Additional Context
          description: Add any other context about the security issue here.
